# Generated by Django 5.1.4 on 2024-12-10 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_lesson_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_exam', to=settings.AUTH_USER_MODEL),
        ),
    ]
